//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Avengers.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ingles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ingles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Avengers.Recursos.Ingles", typeof(Ingles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        internal static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add and New.
        /// </summary>
        internal static string btnAddNew {
            get {
                return ResourceManager.GetString("btnAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string btnChange {
            get {
                return ResourceManager.GetString("btnChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clean.
        /// </summary>
        internal static string btnClean {
            get {
                return ResourceManager.GetString("btnClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string btnCloseTab {
            get {
                return ResourceManager.GetString("btnCloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        internal static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btnDeleteUser {
            get {
                return ResourceManager.GetString("btnDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a                  Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify.
        /// </summary>
        internal static string btnModUser {
            get {
                return ResourceManager.GetString("btnModUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        internal static string btnNewUser {
            get {
                return ResourceManager.GetString("btnNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orders.
        /// </summary>
        internal static string btnOrders {
            get {
                return ResourceManager.GetString("btnOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.
        /// </summary>
        internal static string btnSys {
            get {
                return ResourceManager.GetString("btnSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string button2 {
            get {
                return ResourceManager.GetString("button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleted.
        /// </summary>
        internal static string ckDel {
            get {
                return ResourceManager.GetString("ckDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        internal static string customers {
            get {
                return ResourceManager.GetString("customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password:.
        /// </summary>
        internal static string lblNewPass {
            get {
                return ResourceManager.GetString("lblNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current password:.
        /// </summary>
        internal static string lblOldPass {
            get {
                return ResourceManager.GetString("lblOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lblP {
            get {
                return ResourceManager.GetString("lblP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions.
        /// </summary>
        internal static string lblPermList {
            get {
                return ResourceManager.GetString("lblPermList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat new password:.
        /// </summary>
        internal static string lblRepPass {
            get {
                return ResourceManager.GetString("lblRepPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role:.
        /// </summary>
        internal static string lblRol {
            get {
                return ResourceManager.GetString("lblRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Role Name:.
        /// </summary>
        internal static string lblRoleName {
            get {
                return ResourceManager.GetString("lblRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selected permissions.
        /// </summary>
        internal static string lblSelectedPerm {
            get {
                return ResourceManager.GetString("lblSelectedPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Languaje.
        /// </summary>
        internal static string lblSelectIdioma {
            get {
                return ResourceManager.GetString("lblSelectIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string lblU {
            get {
                return ResourceManager.GetString("lblU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
